FROM node:20

WORKDIR /usuarios

COPY src/controllers/usuariosController.js usuariosController.js
COPY src/models/usuariosModel.js usuariosModel.js
COPY index.js .

RUN npm init --yes
RUN npm install express morgan mysql mysql2 axios

EXPOSE 3001

CMD node src/index.js